### ISSUE TITLE
Consider making puzzle marker optional

### ISSUE THREAD

**Issue by php-coder** [yegor256/pdd#81]
At this time, author always have to specify at least one marker.

In order to support other workflows, it's better to make a marker optional. It makes possible to commit changes without related issue (time, etc), for example.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder sounds like an interesting suggestion, but it will break the entire idea of PDD, I believe. All puzzles should have some "parent" issues, in order to create a hierarchy. If we put all of them on one level we will seriously simplify the idea... Maybe some projects need that simplicity though. Let's think..)

**Comment by php-coder** [comment]
That's also make sense.

In any way, I do believe that assumptions/intentions/rules should be documented to make it clear what users should expect and also to limit of the scope where this tool could be used.

**Comment by yegor256** [comment]
@php-coder how about dca9da9 ?

**Comment by php-coder** [comment]
@yegor256 Super! Thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#81` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#81](https://github.com/yegor256/pdd/issues/81) was not in scope
